#!/usr/bin/env python3
"""
Generate firmware/config/IcaoIataTable.h from OurAirports public-domain data.

Usage:
    python tools/gen_icao_iata.py                        # download fresh CSV
    python tools/gen_icao_iata.py --local airports.csv   # use a local copy
"""

import argparse
import csv
import sys
import urllib.request
from pathlib import Path

CSV_URL = "https://davidmegginson.github.io/ourairports-data/airports.csv"
OUT_PATH = Path(__file__).parent.parent / "firmware" / "config" / "IcaoIataTable.h"


def char_list(s):
    return "{" + ",".join(f"'{c}'" for c in s) + "}"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--local", metavar="FILE",
                        help="Use a local airports.csv instead of downloading")
    args = parser.parse_args()

    if args.local:
        with open(args.local, newline="", encoding="utf-8") as f:
            rows = list(csv.DictReader(f))
    else:
        print(f"Downloading {CSV_URL} ...", file=sys.stderr)
        with urllib.request.urlopen(CSV_URL) as resp:
            content = resp.read().decode("utf-8")
        rows = list(csv.DictReader(content.splitlines()))

    pairs = []
    seen = set()
    for row in rows:
        icao = row.get("ident", "").strip().upper()
        iata = row.get("iata_code", "").strip().upper()
        # Strict: 4-char alpha ICAO, 3-char alpha IATA, no duplicates
        if (len(icao) == 4 and icao.isalpha() and
                len(iata) == 3 and iata.isalpha() and
                icao not in seen):
            pairs.append((icao, iata))
            seen.add(icao)

    pairs.sort(key=lambda x: x[0])
    n = len(pairs)
    print(f"Found {n} ICAO→IATA pairs", file=sys.stderr)

    lines = [
        "// Auto-generated by tools/gen_icao_iata.py — do not edit by hand.",
        "// Source: OurAirports (https://ourairports.com/data/) — public domain.",
        f"// {n} airports sorted by ICAO code; binary-searched at runtime.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "struct IcaoIata { char icao[4]; char iata[3]; };  // 7 bytes, no null terminators",
        "",
        f"static constexpr uint16_t kIcaoIataCount = {n};",
        "",
        "static const IcaoIata kIcaoIataTable[] PROGMEM = {",
    ]

    for i, (icao, iata) in enumerate(pairs):
        comma = "," if i < n - 1 else ""
        lines.append(f"    {{{char_list(icao)},{char_list(iata)}}}{comma}")

    lines += [
        "};",
        "",
        "// Binary search: returns true and fills outIata[4] (3 chars + '\\0') on hit.",
        "inline bool icaoToIata(const char *icao, char outIata[4]) {",
        "    int lo = 0, hi = (int)kIcaoIataCount - 1;",
        "    while (lo <= hi) {",
        "        int mid = (lo + hi) / 2;",
        "        IcaoIata e;",
        "        memcpy_P(&e, &kIcaoIataTable[mid], sizeof(IcaoIata));",
        "        int c = strncmp(icao, e.icao, 4);",
        "        if (c == 0) {",
        "            outIata[0]=e.iata[0]; outIata[1]=e.iata[1];",
        "            outIata[2]=e.iata[2]; outIata[3]='\\0';",
        "            return true;",
        "        }",
        "        if (c < 0) hi = mid - 1; else lo = mid + 1;",
        "    }",
        "    outIata[0] = '\\0';",
        "    return false;",
        "}",
        "",
    ]

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written {OUT_PATH}  ({n} entries, ~{n * 7 // 1024} KB flash)", file=sys.stderr)


if __name__ == "__main__":
    main()
